### ISSUE TITLE
[Eval Tools list] "Start filter assistant" button does not work on Safari

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-eval-tools#100]
Tested on Safari 15.5
Click on the "Start filter assistant" button throws the following logs in the console:
```
TypeError: undefined is not an object (evaluating 'currentFilter.options')      list-of-evaluation-tools:36511
ReferenceError: Cannot access uninitialized variable.                           list-of-evaluation-tools:36921
```

It works on Chrome and Firefox

**Comment by VeraLange** [comment]
We think this may have been caused by a temporary bug that has been resolved. We tested in Safari ourselves and the button works, could you check whether it works for you as well? Thanks!

**Comment by carlosapaduarte** [comment]
Can you send me the link where I can test the updated version? Thanks!

**Comment by VeraLange** [comment]
Here's the link to [the updated version](https://master--wai-evaluation-tools-list.netlify.app/list-of-evaluation-tools/)

**Comment by carlosapaduarte** [comment]
It's working fine now. Thanks!
