### ISSUE TITLE
[Filter Assistant] Info box in the "Purpose" step presents questionable information

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-eval-tools#101]
The sentence "Automated tools can currently find about 20% of accessibility issues" is debatable. There is no clear source that can be cited. If I'm not mistaken, a recent study by Deque places this closer to 50%, but I've seen numbers ranging from 20% to 50%.

I don't think the W3C should commit to a number here. Something like "Currently, automated tools are not able to detect all accessibility issues" would be wiser.

**Comment by VeraLange** [comment]
Valid point. The text has been changed. Thanks!
