### ISSUE TITLE
[Filter assistant] Sub-heading in the "Type of tool" step needs improvement

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-eval-tools#102]
It currently reads "Do you prefer a type of tool integration?"

The sentence does not make sense. Furthermore, I don't think using "integration" is a good choice. Options "Desktop application" and "Mobile application" are not really integrations.

**Comment by VeraLange** [comment]
The sentence has been changed to: "Should the tool work separately or integrated within other applications and environments?"

We hope this prevents confusion, however, the options in this step of the filter assistant are pretty diverse.
