### ISSUE TITLE
Supported files

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-tools#111]
1. I'm not sure what this is? Is it the report output?

2. Why is the order different in the submission form? Wouldn't we want HTML first?

3. "Open Documents Format (ODF)" -> Open Document Format (ODF)

**Comment by VeraLange** [comment]
1. We changed the title to "File to evaluate", consistent with other filter titles.
2. The order of both lists have been aligned. 
3. Fixed.
