### ISSUE TITLE
full WAI website header

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-tools#113]
Reminder that EOWG agreed on full WAI website header, not minimal header.

**Comment by shawna-slh** [comment]
more info in: https://github.com/w3c/wai-course-list/issues/202

**Comment by mhansma96** [comment]
@SteveALee Can we put back the "old" header easily?

**Comment by SteveALee** [comment]
Yup. Leticia did for course list.

There was a problem with the search form breaking a feature but that's be fixed.

**Comment by mhansma96** [comment]
Is this easily mergeable from somewhere? I believe you did this the last time to make it the one that it is now
