### ISSUE TITLE
[high] Information icon alternative text

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-eval-tools#114]
The alternative text on information icons seems to be a bit off.

For example:

```<img aria-label="Info Purpose" data-toggletip-content="Type of evaluation a tool supports" tabindex="0" src="/content-images/wai-evaluation-tools-list/info.png">```

The alternative text (implemented using `aria-label`) should really be 'Type of evaluation a tool supports'. Otherwise, some assistive tech users will not get the same information.

**Comment by VeraLange** [comment]
The content of the aria-labels has been changed accordingly. Thanks!
