### ISSUE TITLE
Show all tools -> Clear all filters ?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-tools#12]
When I have filter(s), it has:

> 18 Results Selected Filters: WCAG 2.0 — W3C Web Content Accessibility Guidelines 2.0 [Show all tools]

However, "Show all tools" doesn't really show all tools (at the bottom of the list it says "Show more"). I wonder if this button should instead be "Clear all filters"? Or is that a bit of a hard concept for some users?

Maybe if issue 11's resolution is that we can show all tools and not have the button at the bottom to show more, then this button is OK as Show all tools? Or would "Clear all filters" still be more accurate?

(Edited to fix format of post. – Eric)

**Comment by yatil** [comment]
The button used to be [clear filters] but it felt like rather hard to grasp as a concept. Resolution to #11 is to show all, so clearing filters shows all. I guess we can stick with show all now.

**Comment by shawna-slh** [comment]
OK.
