### ISSUE TITLE
Authoring Tools not clear as filter section title

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-eval-tools#14]
"Authoring Tools" is not really what this section filters for. Suggest a change to Authoring Tool PlugIns

**Comment by yatil** [comment]
I think the people this is aimed at know that those are eval tools that work in authoring tools. I welcome clarifying changes of the description of this item.

**Comment by shawna-slh** [comment]
I think some people using this tools list will not understand if the category is called just "Authoring Tools". (If fact, even I don't really know what this means.) If Sharron's suggestion "Authoring Tool PlugIns" does not work, how about something like, "Works with Authoring Tools"?

**Comment by yatil** [comment]
Hm… I hadn’t seen the suggestion… (Jet-lag confusion) What about calling it “PlugIns for…” and roll Browser plugins and authoring tool plugins in one category? (Browser evolve into ATs more and more anyway.)

**Comment by nitedog** [comment]
What is the problem with keeping them separate? I think these are distinct use-cases (one is usually more for front-end developers, and the other usually more for (non-techy) content editors) - by the way, we spent a lot of time on terms finding for the past version of this tool, so the more you reuse, the easier it _might_ be!

**Comment by yatil** [comment]
It is no problem, I just wanted to make a suggestion for brevity.
