### ISSUE TITLE
Allowing people to add filter criteria

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-eval-tools#15]
This is not working well and ends up with strange, badly worded filter criteria such as these:
Under "Automatically checks," a filter option is ..."any part color of the page thanks to the color picker" - what does this mean? 

Under "Online Service," a filter option says "also firefox addon" what does that actually mean? If these are being generated by submission form, need a final OK and clarity filter from staff (sorry but true).

Perhaps add to their internal description but not to filtering options.  It will get unruly and incomprehensible pretty fast.

**Comment by yatil** [comment]
In the grand picture we want people to be able to add new filters, but it requires some manual screening of the submissions. Maybe we could think of another way to handle this?

**Comment by schantzwebconsulting** [comment]
There are more search options than tools.  Filters like this would be useful in a list of hundreds or thousands of tools, but if I had that many records I might use SOLR instead.  Here they just feel clunky.  How long could this list eventually become?  I suggest hiding the filters, possibly inside an accordion above the list.

**Comment by yatil** [comment]
We’re in the progress of collecting data. The previous list had more tools. Apart from that I think it is much easier to be able to narrow it down to some tools depending on the needs.
