### ISSUE TITLE
date format mmm

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-tools#18]
Use mmm for month, e.g., 2014-Nov-12

Priority: For dates that really matter, this is a requirement. Given the dates are not critical in this list, if it's a huge challenge, then maybe can let it go?

**Comment by yatil** [comment]
While it is certainly somehow possible to reformat the dates, they are [ISO8601 formatted dates](https://en.wikipedia.org/wiki/ISO_8601) which are unambiguous.

**Comment by nitedog** [comment]
I think they are ambiguous to people who don't know that they are ISO format, or what ISO format is. In the US it is common to have the day first, then the month, but in Europe it is often the other way round. Making the month non-numeric makes it really unambiguous IMHO. Again, if this is not too much of a challenge for you (I can't tell from your response).

**Comment by yatil** [comment]
I have changed the date format. (I find it way harder to read like this – probably as I’m not used to also translate parts of a date and it is also harder to match a known date pattern as a non-native non-US speaker. But if the standard is ambiguous for some people, I’m okay with keeping the change.)

**Comment by shawna-slh** [comment]
you had yyyy-mm-dd
I suggested yyyy-mmm-dd
but now you have dd mmm yyyy

dd mmm yyyy is harder for me to read, too. Also, in this case, the year is much more important than the day of the month, thus it makes sense to put year first. So why not yyyy-mmm-dd (e.g., 2014-Nov-12) ?

**Comment by yatil** [comment]
Will change it.
