### ISSUE TITLE
Remove link for the term "web content" in the opening sentence 

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-tools#19]
@nitedog:

> Remove link for the term "web content" in the opening sentence - odd to have this particular term highlighted, and kind of sends people away.

**Comment by yatil** [comment]
As it can be seen in discussion of #6, the group decided on the linking:
http://www.w3.org/2014/11/07-eo-minutes#item02

**Comment by sharronrush** [comment]
Yes the link was determined to be necessary to avoid having to make too many qualifications within the sentence.
