### ISSUE TITLE
Rewording into paragraph & link to selecting web accessibility eval tools

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-tools#20]
@nitedog:

> Provide a brief explanation of what this page is about - consider such rewording: "Web accessibility evaluation tools are software programs or online services that help you determine if web content meets accessibility guidelines. While web accessibility evaluation tools can significantly reduce the time and effort to evaluate websites, no tool can automatically determine the accessibility of websites. This page provides a list of evaluation tools that you can filter to find ones that match your particular needs. [Selecting web accessibility evaluation tools](http://www.w3.org/WAI/eval/selectingtools) provides more background and information."

**Comment by yatil** [comment]
I think it is a bit long, I don’t think it is valuable to have half a screen of text before the actual tool. (If we want such a long text we want an expand collapse button that is collapsed when the page is accessed.)

**Comment by yatil** [comment]
Also, @nitedog:

> Remove the sentence "While web accessibility evaluation tools can significantly reduce the time and effort to evaluate websites, no tool can automatically determine the accessibility of websites." - we should link to the "Selecting Tools" doc instead, for people who are new to accessibility and evaluation.

(I think it is the same issue.)

**Comment by shawna-slh** [comment]
"whenever feasible, put linked documents at the end of sentences." https://www.w3.org/WAI/EO/wiki/Style#Document_links_in_sentences
For more information on [@@ maybe say more about specifically what's there], see _Selecting web accessibility evaluation tools_.
