### ISSUE TITLE
Top submission link placement

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-tools#21]
@nitedog:

> Remove or better position (and rephrase) "Submit an evaluation tool." - Looks a bit odd at the end of that paragraph (I like the button version very much, though). Also, it should be "Provide information about an evaluation tool" or such, especially if it is a text-link (as opposed to a buttony-link)

**Comment by shawna-slh** [comment]
I'm not keen on having that link/button in the top paragraph at all. Think of the primary audience... the huge majority will not be submitting a tool, and therefore I think it's too distracting at the top.
