### ISSUE TITLE
Change submit button wording

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-tools#23]
@nitedog:

> Change "Submit your tool" to "List your tool" or such - "submit your tool" doesn't make sense

**Comment by yatil** [comment]
For reference: The previous wording was:

> Submit Information about Web Accessibility Evaluation Tools

We can go back to this in the intro at least. It is a bit long for the button. I always read it as “Submit your tool to the list”…

**Comment by sharronrush** [comment]
List Your Tool seems right to me

**Comment by LydiaHarkey** [comment]
If keeping with the same wording, I suggest 'Submit a Tool' as it may indicate that one can send in their tool by clicking on the submit button whereas 'List your tool' suggest the submitter can lists their tools without information. another option would be is to label the button as 'Evaluation Tool' or 'Submit Evaluation Tool'

**Comment by iadawn** [comment]
"Add your tool"?
