### ISSUE TITLE
Change Details to Tool features?

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-tools#28]
@nitedog:

> Consider changing "Details" to "Tool features"? - probably for discussion but these are not really "details" as such, though maybe "features" is too jargony? Would be a good link to the features doc, though.

**Comment by yatil** [comment]
I think that details pretty well describes the functionality. I can see having feature there as well. Probably we need to speak about what we want to display where, additionally

**Comment by shawna-slh** [comment]
Minor issue is that now there is a filter category called "Features" that is much more limited than the info under the "Tool Features" twisty. I actually think they are "Details" -- details about the tool.
I don't think this is a significant issue -- although we like to keep our quality high -- so I can't decide whether it's worth spending time discussing in EOWG...

**Comment by yatil** [comment]
I have changed it to “Detailed Information” – as we’re using a full line for this we can be more verbatim.

**Comment by LydiaHarkey** [comment]
I actually liked 'Detailed Information'

**Comment by shawna-slh** [comment]
I like the solution where the tool name is lighter gray. I assume it's still at least Level A? :-)

minor: You don't need quotes around the tool name.

**Comment by yatil** [comment]
Double-A of course.
![web_accessibility_evaluation_tools_list](https://cloud.githubusercontent.com/assets/58862/5209590/c9fe8126-75c0-11e4-80b9-1d0a0e8cc8ee.png)

minor: I like the quotes.
