### ISSUE TITLE
Link to tool homepage in description

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-tools#29]
@nitedog:

> Consider adding link to tool homepage in the description - think that some people may not immediately realize that the heading is also a link.

**Comment by yatil** [comment]
From which page? The submission and acknowledge page have links back, and the main page is the tool home page?!

**Comment by nitedog** [comment]
Sorry - clarification - each list-entry has the name of the tool that serves as both a heading and as a link to the homepage of the evaluation tool at the same time. This dual-function may not be very clear to everyone. Actually, I first looked for the link to the homepage of the tool within the "description" section, then, when I didn't find a link, I decided to hover the mouse over the heading to explore whether it is a heading.

**Comment by LydiaHarkey** [comment]
I noticed that within some of the description section of the tools, the name of the tool links to the homepage of the evaluation tool whereas some of the tools in the description section do not have links. Ex. http://www.508checker.com/index.php has a link on the header and within the description section but A- Tester heading which is linked has A-Tester in the description section that is not linked. Should there be consistency if the tool is written in the description that they are also linked to the same URL address as the headings?

![image](https://cloud.githubusercontent.com/assets/9736007/5156585/c44c87d0-7293-11e4-8a8a-e807d2035ae2.png)

**Comment by yatil** [comment]
We currently link things in the description that is programmatically identifiable as an URL, 508checker.com is, A-Tester is obviously not.

**Comment by LydiaHarkey** [comment]
Oh, ok. I was thinking if the heading was mentioned in the description section then it would also have the same link as the header. I understand now. Thanks!

**Comment by yatil** [comment]
Added a link to the description in commit 170bbb34e50fa16cbc7afcb252dcd26a40ca63f9 [(1)](https://github.com/w3c/wai-eval-tools/commit/170bbb34e50fa16cbc7afcb252dcd26a40ca63f9#diff-2)

and added the URL as the last bullet point in the description in f5c0e7eedf72c77e492c412cff9b9a94a1b403a3

**Comment by shawna-slh** [comment]
I _strongly_ do not like "Link" repeated for each one. Most people noticed that the tool name in the heading is a link. For those who don't, we now have a link in the detailed information "URL:" I think this is sufficient, and I suggest removing the "Link" from the main description.

**Comment by shawna-slh** [comment]
Separate point: The links within the descriptions are causing some people to stumble -- including Vivienne and Lydia. What about _not_ linking anything in the description? Submitters can put an address there, but we don't make it link. (I do not feel strongly about this, though.)

**Comment by yatil** [comment]
@slhenry, I have removed the “Link” for now, I hope that the URL in the details works for @nitedog. I have already removed the linking of other URLs in the description, as discussed in last call and noted in the commit above.

**Comment by yatil** [comment]
I have added the link as suggested by @nitedog this morning: ee33023b2b8d4560616345f22dca744a82f79b0b

**Comment by sharronrush** [comment]
Yes, looks good.

**Comment by AndrewArch** [comment]
@slhenry @yatil, Not sure I like the removal of in-description links (e.g. http://goo.gl/L7gCXu ) - now means one has to cut and paste to follow-up, rather than just activating the provided URI

**Comment by shawna-slh** [comment]
/me looks at version on Friday 5 Dec 10:30E ... I don't understand @AndrewArch 's comment because it looks like the URIS are linked. but also I see that the links look different than last time I looked at them and I don't like it as much... darn, wish I had noticed that to discussion in EOWG today...

**Comment by yatil** [comment]
@slhenry: @AndrewArch commented on links _inside_ descriptions, for example in this [entry from google](http://w3c.github.io/wai-eval-tools/#accessibility-developer-tools). 

As noted above, the change to the links was made in response to @nitedog’s request.

**Comment by shawna-slh** [comment]
@AndrewArch re: link inside the description. Andrew, these are not significant links. The URI to the tool is linked. EOWG decide that also having linked text within the descriptions was more confusing than helpful. (Also, a vendor could put them in inappropriately.) In any case, there are so few that I think it's OK for URIs within the descriptions not be linked.

**Comment by shawna-slh** [comment]
Issue: Tools Links. Personally, I think having the URI always visible in the main area is distracting. However, I do see that the link provides some interesting information on some of the tools. So I'm OK with having it there; however, I do think the design needs to be tweaked to minimize the distraction.

Part of the problem is that the description, the parenthetical information, the word "Link", and the link itself are all different font size, weight, and/or colour. I've got a couple of ideas on what to do with those, but it's too much typing right now, so let's talk via phone, please. Thanks.

**Comment by yatil** [comment]
@slhenry @AndrewArch: Also in the new, improved submission form, we ask people not to use Links in descriptions. The text will say “Please enter only plain text, no HTML is allowed. URIs won’t be linked.”

**Comment by yatil** [comment]
This was resolved in the commits 3e5c073 and  a561ccc.
