### ISSUE TITLE
add permalink to each entry

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-eval-tools#35]
Minor - might be nice to have a permalink anchor for each tool entry, so that we can refer to individual tools within the list.

**Comment by shawna-slh** [comment]
Symbol:
The current character used is a copyedit mark for "paragraph" and that messes with my x-copyediter brain. :-)
/me goes to see what's used for the tutorials.... doh! it's similar. That's a change that I missed. The tutorials used to be a different symbol - like a chain link.
I suggest we not use the paragraph symbol in either place.

**Comment by shawna-slh** [comment]
Appearing on focus: I'm not sure about this. Seems like it could add more confusion -- and it would need an explanation (e.g., Tips in the left column under everything else).
I was one of the people who thought having a permalink all the time would add clutter. However, I was envisioning it nearer the tool name. I'm fine OK with it over on the right all the time.
