### ISSUE TITLE
Duplication in Features Filter

### ISSUE THREAD

**Issue by LydiaHarkey** [w3c/wai-eval-tools#38]
In the Features Filter - there is two 'Displaying information with Web pages' the difference seems to be the letter 'w' in web one is capitalized and the second filter is not. 
![feature_filter](https://cloud.githubusercontent.com/assets/9736007/5156523/231a5734-728e-11e4-964c-15f59a049b0b.JPG)

**Comment by yatil** [comment]
Hi Lydia, the reason for this is that the submission page on the W3C page and the data that we will collect in the new version differ, I have corrected those entries.
