### ISSUE TITLE
Permalink symbol

### ISSUE THREAD

**Issue by yatil** [w3c/wai-eval-tools#40]
To branch off from #35: 

@slhenry:

> Symbol:
> The current character used is a copyedit mark for "paragraph" and that messes with my x-copyediter brain. :-)
> /me goes to see what's used for the tutorials.... doh! it's similar. That's a change that I missed. The tutorials used to be a different symbol - like a chain link.
> I suggest we not use the paragraph symbol in either place.

**Comment by yatil** [comment]
Another commonly used symbol is `§` (it is used in the new https://specs.webplatform.org/#core) as well.

**Comment by yatil** [comment]
I have added an anchor icon as a symbol for a permalink.

**Comment by sharronrush** [comment]
Still not sure why this was needed but it looks fine to me.
