### ISSUE TITLE
Link to accessibility information

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-eval-tools#42]
I like the way this is done in the fake tool. I would only suggest that we add the line to all of the others to indicate "Accessibility statement: None provided" so that people are encouraged to do submit that info.

**Comment by yatil** [comment]
Question is what we do with the tools we already have and that don’t have such information provided.

**Comment by AndrewArch** [comment]
Invite them to update their info - in the meantime don't display anything (same goes for people who don't provide any info - don't display anything, rather than 'none provided')

**Comment by shawna-slh** [comment]
per EOWG discussion on 5 Dec - showing [none provided] will encourage them to provide it. :-)

**Comment by shawna-slh** [comment]
this has disappeared from the Filter options... maybe because at the moment none have it? but I think we want it there for the announcements (and I need to know what it says for drafting them :-)

**Comment by yatil** [comment]
Actually there is nothing I can do about it. It says “Tools providing accessibility information (# Tools)”. [That was the reason why I had the example tool in there.]

**Comment by shawna-slh** [comment]
@nitedog I really want that option to show in the filters when we announce on Wednesday. Until we get a tool that provides it, can we put an obviously "dummy"/placeholder listing very last in the list -- e.g., starting with a Z, with title something like Z-placeholder and all the fields blank except for that one that has something like: "[link here]"?
Or do you have another idea?

**Comment by nitedog** [comment]
We now have a tool that has accessibility information, so that selection option should become visible again very soon. I was not aware that the option cannot be forced to display (with "0" tools).
