### ISSUE TITLE
provide feedback mechanism

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-eval-tools#47]
Request: provide a way for readers to provide feedback, such as a broken link or wrong information.
Rationale: not easy to find in the page footer, and also not clear that "feedback welcome" also refers to bug reports (such as a broken link or wrong information).
Suggestion: add a mailto: link under "Add your tool!" button, saying something like "Send comments" or "Provide feedback" or "Problem with the list?" (very open it wording ideas).

**Comment by yatil** [comment]
Hm. Haven’t remembered that this issue was open for this round of updates, but I think it would be a minor addition. Probably a `mailto:` link would be sufficient?

**Comment by nitedog** [comment]
I forgot as well. I don't feel strongly about it but should be quite easy. I will add it to the survey for later discussion with EO.

**Comment by shawna-slh** [comment]
[revision](https://master--wai-evaluation-tools-list.netlify.app/list-of-evaluation-tools/) has WAI-site-standard "Help improve this page" box.
