### ISSUE TITLE
Text edits to intro

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-eval-tools#6]
To me, the use of "web sites" sounds a bit limiting and not inclusive enough.  Also think we need to emphasize the need for human judgement a bit more. Therefore, suggest:

Web accessibility evaluation tools are software programs or online services that help determine if a web page or application meets accessibility guidelines.  While web accessibility evaluation tools can significantly reduce the time and effort to evaluate websites, no tool can automatically determine the accessibility of websites. Human judgement will still be needed. 
W3C does not endorse specific products.  Information on this page is provided by vendors and others. See Important Disclaimer. Submit an evaluation tool.  [comment: this link does not seem to be working by the way]

**Comment by shawna-slh** [comment]
In the 7 Nov EOWG telecon, we discussed several options for the first sentence. Minutes: http://www.w3.org/2014/11/07-eo-minutes#item02 There were differing opinions and no one felt super strong for or against any.

I think we finally settled on the suggestion of: Web accessibility evaluation tools are software programs or online services that help determine if <a href="http://www.w3.org/WAI/intro/accessibility.php#content">web content</a> meets accessibility guidelines.

**Comment by sharronrush** [comment]
Yes that was the final decision.  To use the term "web
content" and link to the WAI definition.

At 01:25 PM 11/7/2014, shawn_slh wrote:
In the 7 Nov EOWG telecon, we
discussed several options for the first sentence. Minutes:

http://www.w3.org/2014/11/07-eo-minutes#item02 There were differing
opinions and no one felt super strong for or against any.
I think we finally settled on the suggestion of: Web accessibility
evaluation tools are software programs or online services that help
determine if
web
content meets accessibility guidelines.
­
Reply to this email directly or

view it on GitHub.

```
            This email is free from viruses and malware because avast! Antivirus protection is active.
```

**Comment by shawna-slh** [comment]
Sharron had also recommended adding " Human judgement will still be needed. " EOWG forgot to discuss that last week, so that's still open.

**Comment by yatil** [comment]
Thanks for pointing that out.
