### ISSUE TITLE
Text edits to filter criteria

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-eval-tools#7]
1. "Assistance" is the wrong word for this category.  Suggest "Features" or "Competencies" or something more accurate.  
2. Under "Automatically checks," change "any part color of the page thanks to the color picker" - what does this mean? Accurately describe the capacity and remove "thanks to the color picker"
3. "Authoring Tools" - this category made me realize that perhaps we need a "Help" page that explains some of these obscure filter criteria.  Does this mean that it checks the validity of output from these authoring tools? Why would a Dreamweaver Checker need a separate tool? Won't the output be tested the same as any other output? This is not clear.
4. Online Service - what does "also firefox addon" mean? If these are being generated by submission form, need a final OK and clarity filter from staff (sorry but true)

**Comment by yatil** [comment]
Thanks Sharron, I addressed item 1 in the commit above.

2 & 4 were addressed earlier this morning (we allow users to enter any data in “other” fields in the submission form, I cleaned the data set.)

3: I think the people this is aimed at know that those are eval tools that work in authoring tools. I welcome clarifying changes of the description of this item.

**Comment by yatil** [comment]
Closing as this was splitted into multiple issues:

1: #13 
2: #15 
3: #14
4: #15 

Sorry for not having noticed this earlier.
