### ISSUE TITLE
minor - overall margin

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-tools#8]
It feels tight. I would prefer a little more margin on the right and left.
This is very minor. I'm fine leaving it as is if anyone disagrees.

**Comment by yatil** [comment]
It’s consistent with the tutorials, so I’d vote for leaving it as it is. The margins inside the page look arbitrary now that we’ve changed to the one col layout for the results, I need to fix that.

**Comment by sharronrush** [comment]
seems OK no strong feelings
