### ISSUE TITLE
Submit a tool form - Add/remove feature buttons do not work when I use my keyboard

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-eval-tools#84]
https://master--wai-evaluation-tools-list.netlify.app/list-of-evaluation-tools/submit-a-tool

The add/remove feature buttons do not work when I hit enter. I had to use my mouse. 

Add/remove language buttons have the same issue.

**Comment by VeraLange** [comment]
The buttons should now be accessible by keyboard.
