### ISSUE TITLE
[medium] Fieldset/legend pattern for input fields

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-eval-tools#88]
I am not sure about the fieldset/legend pattern used in the submission form input fields. This seems like a peculiar way to do form fields and doesn't seem aligned with the [forms tutorial](https://www.w3.org/WAI/tutorials/forms/labels/).

**Comment by mhansma96** [comment]
We've added area-labels to the legends for the input fields.
Like so: <legend for="title" aria-label="Tool name" class="label-input">Tool name</legend>

Do you think that his will help the problem?

**Comment by iadawn** [comment]
Unfortunately I think this is not the right way to use fieldset/legend or how to do fields with labels. The current code is:

```
<fieldset class="field">
      <legend for="title" aria-label="Tool name" class="label-input">Tool name<span>Required</span></legend>
      <input type="text" id="title" name="title" required="">
</fieldset>
```

I think it should be more like:

```
<div class="field">
    <label for="title" class="label-input">Tool name<span>Required</span></label>
    <input type="text" id="title" name="title" required="">
</div>

Using the fieldset and legend is appropriate for structuring groups but not really the way to do single fields with a label.

**Comment by mhansma96** [comment]
Thanks for the reply and the example on this!
We've aligned the structure of the form accordingly. Please let us know if this has solved the structure issue.

**Comment by iadawn** [comment]
Getting there. It is still using `<legend>` where there should be a `<label>`

```
<div class="field">
      <legend for="title" aria-label="Tool name" class="label-input">Tool name<span>Required</span></legend>
      <input type="text" id="title" name="title" required="">
</div>
```

And you should also remove the `aria-label`. It is unnecessary if you use the `<label>` in this way.

```
<div class="field">
    <label for="title" class="label-input">Tool name<span>Required</span></label>
    <input type="text" id="title" name="title" required="">
</div>

```

**Comment by mhansma96** [comment]
I think it should be according to the standards now. Thanks for the input on label/aria-label. The changes are live.

**Comment by iadawn** [comment]
That looks good. One more thing (sorry :))... grouping for radio and checkbox groups. Currently this is like:

```
<div class="field" id="purpose">
      <div class="fieldheader">
        <label for="tool-purpose" class="label-input">Purpose<span class="short-sub">(Required)</span></label>
      </div>
      <p>What type of evaluations does this tool support?</p>
      <div class="field-group">
        
          <div class="radio-field">
            <input type="checkbox" name="purpose[]" id="tool-purpose-automated" value="Automated testing" group="purpose" required="">
            <label for="tool-purpose-automated">Automated testing</label>
          </div>
...
        
      </div>
  </div>
```

This is where fieldset/legend come in. And there are other ways to do this but if you go with:

```
<fieldset class="field" id="purpose">
      <div class="fieldheader">
        <legend for="tool-purpose" class="label-input">Purpose<span class="short-sub">(Required)</span></legend>
      </div>
      <p>What type of evaluations does this tool support?</p>
      <div class="field-group">
        
          <div class="radio-field">
            <input type="checkbox" name="purpose[]" id="tool-purpose-automated" value="Automated testing" group="purpose" required="">
            <label for="tool-purpose-automated">Automated testing</label>
          </div>
...
        
      </div>
  </fieldset>
```

So the outer containing `<fieldset>` groups all the controls together, and the `<legend>` provides a label for the group. Hope this makes sense!

**Comment by mhansma96** [comment]
Thanks for providing this expertise. I believe the checkbox-fields should be according to that example now.
