### ISSUE TITLE
[low] Purpose of information icons

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-eval-tools#89]
The information icons, for example in Purpose or Scope of evaluation, don't seem to do anything. This is on MS Edge Chromium.

The `aria-label` on the image will make this unusable by screen readers I would have thought. Not sure of the value of using the `<abbr>`.

```
<abbr title="W3C Web Content Accessibility Guidelines 2.1" class="toggletip-container">
  <img aria-label="more info" data-toggletip-content="W3C Web Content Accessibility Guidelines 2.1" src="/content-images/wai-evaluation-tools-list/info.png">
  <span class="toggletip-span-inline" role="status"></span>
</abbr>
```

**Comment by MicheleAWilliams-A11y** [comment]
The <abbr> tag is working as designed for me, which means it shows a browser default tooltip on mouse hover (Chrome on a Mac). 

**However**, this won't be accessible for sighted non-mouse users (such as sighted keyboard & voice control users) nor for mouse or adaptive hardware users who find the hover action difficult to accomplish. 

It would be better to use a focusable element that shows/hides upon user interaction (mouse and keyboard) and shows a more visible custom tooltip as in: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tooltip_Role

This also relates to the icons on the "List of Evaluation Tools" page, Issue #83.

**Comment by VeraLange** [comment]
Recently we made some changes to the keyboard accessibility of the page. This should also address this issue and make the information icon accessible as a toggle-able element, for mouse and non-mouse users.

Could you double-check if this works for you now?

**Comment by MicheleAWilliams-A11y** [comment]
If it's from this page then, yes, works perfectly now: https://master--wai-evaluation-tools-list.netlify.app/list-of-evaluation-tools/

**Comment by iadawn** [comment]
Keyboard seems to be working correctly now. I am still not sure about the use of `aria-label`. As an `<img>` surely using `alt` would be the most appropriate and robust?

**Comment by mhansma96** [comment]
@MicheleAWilliams-A11y That's the one, thanks for checking!

@iadawn Good to hear! We've changed the aria-label attributes for the images into alt, which does seem like the appropriate way to add the descriptions. Thanks! It should be live.
