### ISSUE TITLE
minor - version & release date under details

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-eval-tools#9]
I wonder if the version and release date are important enough to be shown always, or if they'd be better collapsed under Details? (Version: 2.9.2, Released: 2014-06-25)

**Comment by iadawn** [comment]
Personally, I would argue for keeping them visible. The value of a tool is often related to how recent it is and how much best practice or new techniques it incorporates. If I see something hasn't been updated for 10 years it tells me something regarding the value or accuracy of the tool. For some tools this isn't necessarily relevant but for many I think it is vital.

**Comment by shawna-slh** [comment]
brief discussion in EOWG on 7 Nov shows some support for leaving it and none for moving it, so I'm totally fine leaving it & am closing the issue.
