### ISSUE TITLE
UI needs more structure (visually and programmatically)

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-eval-tools#91]
The page is very overwhelming visually; it's not clear where to look when first opening the page. I have a few suggestions for updates: 

1. **Provide only 1 main heading text:** The text in the top blue banner ("List of Evaluation Tools") seems to be the main heading but then is overridden by "Tools for web evaluation" below it (which is the actual H1). I suggest removing one of these (and ensuring the remaining wording is the H1).
2. **Move the disclaimer:** The disclaimer is helpful but since the page already has a 2-column visual layout, it seems to add clutter rather than be helpful (and creates an awkward reading/scanning order for people panning with magnification software). I suggest simply putting this text in-line with the other opening text; this will then allow all of the text to run full-width across the top and take up less space. (I know this was brought up before, but looking at it with fresh eyes, it's not easy to see.)
3. **Add subheadings:** Programmatically there's only 1 main heading ("Tools for web evaluation") then one unique H4 ("Sort by") and a series of repeating H4's ("Features", "+Show More Details"). This is not giving a correct sense of the page's layout for screen reader navigation, nor is it helpful for moving between the sections or knowing where you are (e.g., which "Features" am I reading?). I don't believe "Sort by" or "+Show More Details" are headings, but even if they are kept, there need to be more in-between headings to complete proper page structure. 

I suggest that the names of the courses be H3's (which provides a means of jumping through courses and prefaces the "Features" heading), and then adding (visually and programmatically) 2 H2's to give titles for the 2 columns that are visually displayed - as in "Search" and "List of Courses". I gave a talk on screen readers where I used a very similar screen layout and made the case for adding such H2 headings to label columns; the visuals (and my explanation) are in this [A11yTalks YouTube video](https://youtu.be/MwfyJzB3OGM?t=1579) (linked to the exact time).

**Comment by mhansma96** [comment]
We have made changes to the structure of the page.
As for the headings: we've added some changes like making the titles H3 and adding a H2 for the 2 columns (invisible, so it should show up on the screen reader)
