### ISSUE TITLE
The Filter column is hard to distinguish from the main list content

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-eval-tools#92]
Right now the filters on the left have equal "visual weight" with the main content (e.g., same font size, same coloring, etc.) so it's hard to distinguish them when reading (the faint vertical bar isn't enough). 

Since there's already a Search input field above the list, it would be great if people could hide the list of filters on the left to help declutter the main content. 

And/Or perhaps at least visually separate the sections more, such as with more spacing, different coloring, and/or smaller font size. See https://www.w3.org/WAI/fundamentals/ and https://www.w3.org/TR/WCAG21/ as examples of more clearly defined sections.

**Comment by VeraLange** [comment]
The filter section and tools section now have distinct titles.
The spacing between the two sections has been increased by 50%.
