### ISSUE TITLE
[Tool Submission Form] - Missing link in opening paragraph? ("Suggesting a web evaluation tool")

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-eval-tools#94]
Is this text (that appears in the opening paragraphs) missing a link? If nothing else, it seems to be missing quotation marks and/or capitalization.

> Tool users can use the form Suggesting a web evaluation tool to let us know about tools that are not yet included in the list. We will then try to contact the corresponding tool vendor.

**Comment by VeraLange** [comment]
This has been resolved.
