### ISSUE TITLE
[Eval Tools list] Pagination presence is controlled by the filters

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-eval-tools#99]
From what I understood the page on load does not present the possibility to paginate the list. 
But after applying a filter the list becomes paginated (8 results per page). 

This behaviour was quite unexpected :-)
Users should be able to decide on whether the results list is paginated or not (and, ideally, how many results are displayed per page).

**Comment by VeraLange** [comment]
The bug removing pagination on load has been fixed, the list is always paginated now.
